let JkMimeMimeTypeRegistry = function() {
	this.htMime = null;
	this.htExt = null;
};

JkMimeMimeTypeRegistry.prototype._t = { "JkMimeMimeTypeRegistry" : true };
JkMimeMimeTypeRegistry.prototype._tobj = JkMimeMimeTypeRegistry;

JkMimeMimeTypeRegistry.NEW = function() {
	var v = new JkMimeMimeTypeRegistry;
	return v.CTOR_JkMimeMimeTypeRegistry();
};

JkMimeMimeTypeRegistry.prototype.CTOR_JkMimeMimeTypeRegistry = function() {
	this.htExt = null;
	this.htMime = null;
	this.htMime = new Map;
	this.htExt = new Map;
	this.addBuiltinTypes();
	return this;
};

JkMimeMimeTypeRegistry.getSharedInstance = function() {
	if(!(JkMimeMimeTypeRegistry.sharedInstance != null)) {
		JkMimeMimeTypeRegistry.sharedInstance = JkMimeMimeTypeRegistry.NEW();
	}
	return JkMimeMimeTypeRegistry.sharedInstance;
};

JkMimeMimeTypeRegistry.prototype.addBuiltinTypes = function() {
	this.add("*.cpp", "text/x-c++src");
	this.add("*.ogm", "video/x-ogm+ogg");
	this.add("*.epsf", "image/x-eps");
	this.add("*.mpeg", "video/mpeg");
	this.add("*.rmj", "application/vnd.rn-realmedia");
	this.add("*.nes", "application/x-nes-rom");
	this.add("*.rmm", "application/vnd.rn-realmedia");
	this.add("*.gb", "application/x-gameboy-rom");
	this.add("*.qtvr", "video/quicktime");
	this.add("*.ogv", "video/ogg");
	this.add("*.amr", "audio/AMR");
	this.add("*.ogx", "application/ogg");
	this.add("*.rms", "application/vnd.rn-realmedia");
	this.add("*.gf", "application/x-tex-gf");
	this.add("*.gg", "application/x-sms-rom");
	this.add("*.xslt", "application/xml");
	this.add("*.Z", "application/x-compress");
	this.add("*.mdb", "application/vnd.ms-access");
	this.add("*.rmx", "application/vnd.rn-realmedia");
	this.add("*.anim[1-9j]", "video/x-anim");
	this.add("*.gp", "application/x-gnuplot");
	this.add("*.a", "application/x-archive");
	this.add("*.a", "application/x-shared-library-la");
	this.add("*.mdi", "image/vnd.ms-modi");
	this.add("*.c", "text/x-csrc");
	this.add("*.gv", "text/vnd.graphviz");
	this.add("*.m3u8", "audio/x-mpegurl");
	this.add("*.e", "text/x-eiffel");
	this.add("*.pict1", "image/x-pict");
	this.add("*.pict2", "image/x-pict");
	this.add("*.spd", "application/x-font-speedo");
	this.add("*.spc", "application/x-pkcs7-certificates");
	this.add("*.gz", "application/x-gzip");
	this.add("*.dtd", "application/xml-dtd");
	this.add("*.dvi.gz", "application/x-gzdvi");
	this.add("*.h", "text/x-chdr");
	this.add("*.o", "application/x-object");
	this.add("*.spl", "application/x-shockwave-flash");
	this.add("*.etheme", "application/x-e-theme");
	this.add("*.d", "text/x-dsrc");
	this.add("*.sr2", "image/x-sony-sr2");
	this.add("*.t", "text/troff");
	this.add("*.hh", "text/x-c++hdr");
	this.add("*.m", "text/x-objcsrc");
	this.add("*.m", "text/x-matlab");
	this.add("*.ps.bz2", "application/x-bzpostscript");
	this.add("*.anx", "application/annodex");
	this.add("*.crt", "application/x-x509-ca-cert");
	this.add("*.med", "audio/x-mod");
	this.add("*.crw", "image/x-canon-crw");
	this.add("*.spx", "audio/ogg");
	this.add("*.spx", "audio/x-speex");
	this.add("*.xliff", "application/x-xliff");
	this.add("*.ani", "application/x-navi-animation");
	this.add("*.hp", "text/x-c++hdr");
	this.add("*.vhdl", "text/x-vhdl");
	this.add("*.f", "text/x-fortran");
	this.add("*.hs", "text/x-haskell");
	this.add("*.epub", "application/epub+zip");
	this.add("*.kar", "audio/midi");
	this.add("*.mpga", "audio/mpeg");
	this.add("*.dtx", "text/x-tex");
	this.add("*.pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
	this.add("*.dsl", "text/x-dsl");
	this.add("*.csh", "application/x-csh");
	this.add("*.nfo", "text/x-nfo");
	this.add("*.pkr", "application/pgp-keys");
	this.add("*.epsi.bz2", "image/x-bzeps");
	this.add("*.spec", "text/x-rpm-spec");
	this.add("*.f90", "text/x-fortran");
	this.add("*.sql", "text/x-sql");
	this.add("*.css", "text/css");
	this.add("*.f95", "text/x-fortran");
	this.add("*.csv", "text/csv");
	this.add("*.epsi", "image/x-eps");
	this.add("*.tsv", "text/tab-separated-values");
	this.add("*.pla", "audio/x-iriver-pla");
	this.add("*.it", "audio/x-it");
	this.add("*.ape", "audio/x-ape");
	this.add("*.src", "application/x-wais-source");
	this.add("*.tta", "audio/x-tta");
	this.add("*.ttc", "application/x-font-ttf");
	this.add("*.srf", "image/x-sony-srf");
	this.add("*.pln", "application/x-planperfect");
	this.add("*.ttf", "application/x-font-ttf");
	this.add("*.exe", "application/x-ms-dos-executable");
	this.add("*.abw.gz", "application/x-abiword");
	this.add("*.chrt", "application/x-kchart");
	this.add("*.dvi", "application/x-dvi");
	this.add("*.rpm", "application/x-rpm");
	this.add("*.epsf.gz", "image/x-gzeps");
	this.add("*.pls", "audio/x-scpls");
	this.add("*.gcrd", "text/directory");
	this.add("*.t2t", "text/x-txt2tags");
	this.add("*.srt", "application/x-subrip");
	this.add("*.exr", "image/x-exr");
	this.add("*.pntg", "image/x-macpaint");
	this.add("*.ttx", "application/x-font-ttx");
	this.add("*.jad", "text/vnd.sun.j2me.app-descriptor");
	this.add("*.js", "application/javascript");
	this.add("*.latex", "text/x-tex");
	this.add("*.jar", "application/x-java-archive");
	this.add("*.ssa", "text/x-ssa");
	this.add("*.xspf", "application/xspf+xml");
	this.add("*.mgp", "application/x-magicpoint");
	this.add("*.movie", "video/x-sgi-movie");
	this.add("*.cue", "application/x-cue");
	this.add("*.html", "text/html");
	this.add("*.smaf", "application/x-smaf");
	this.add("*.zabw", "application/x-abiword");
	this.add("*.dwg", "image/vnd.dwg");
	this.add("authors", "text/x-authors");
	this.add("*.msod", "image/x-msod");
	this.add("*.xslfo", "text/x-xslfo");
	this.add("*.mrml", "text/x-mrml");
	this.add("*.kdc", "image/x-kodak-kdc");
	this.add("*.cur", "image/x-win-bitmap");
	this.add("*.gnucash", "application/x-gnucash");
	this.add("*.pkipath", "application/pkix-pkipath");
	this.add("*.p", "text/x-pascal");
	this.add("*.patch", "text/x-patch");
	this.add("*.old", "application/x-trash");
	this.add("*.m4", "application/x-m4");
	this.add("*.mbox", "application/mbox");
	this.add("*.png", "image/png");
	this.add("*.stc", "application/vnd.sun.xml.calc.template");
	this.add("*.std", "application/vnd.sun.xml.draw.template");
	this.add("*.arj", "application/x-arj");
	this.add("*.pnm", "image/x-portable-anymap");
	this.add("*.dxf", "image/vnd.dxf");
	this.add("*.sti", "application/vnd.sun.xml.impress.template");
	this.add("*.gplt", "application/x-gnuplot");
	this.add("*.la", "application/x-shared-library-la");
	this.add("*.stm", "audio/x-stm");
	this.add("*.pcf.gz", "application/x-font-pcf");
	this.add("*.kexic", "application/x-kexi-connectiondata");
	this.add("*.arw", "image/x-sony-arw");
	this.add("*.mid", "audio/midi");
	this.add("*.stw", "application/vnd.sun.xml.writer.template");
	this.add("*.mif", "application/x-mif");
	this.add("*.sty", "text/x-tex");
	this.add("*.hpgl", "application/vnd.hp-hpgl");
	this.add("*.asc", "application/pgp-encrypted");
	this.add("*.asc", "application/pgp-keys");
	this.add("*.asc", "text/plain");
	this.add("*.sub", "text/x-microdvd");
	this.add("*.sub", "text/x-mpsub");
	this.add("*.sub", "text/x-subviewer");
	this.add("*.ly", "text/x-lilypond");
	this.add("*.lz", "application/x-lzip");
	this.add("*.kexis", "application/x-kexiproject-shortcut");
	this.add("*.asf", "video/x-ms-asf");
	this.add("*.wmls", "text/vnd.wap.wmlscript");
	this.add("*.s3m", "audio/x-s3m");
	this.add("*.por", "application/x-spss-por");
	this.add("*.asp", "application/x-asp");
	this.add("*.aspx", "application/x-asp");
	this.add("*.ashx", "application/x-asp");
	this.add("*.pot", "application/vnd.ms-powerpoint");
	this.add("*.pot", "text/x-gettext-translation-template");
	this.add("*.sun", "image/x-sun-raster");
	this.add("*.ass", "text/x-ssa");
	this.add("*.rss", "application/rss+xml");
	this.add("*.lha", "application/x-lha");
	this.add("*.md", "application/x-genesis-rom");
	this.add("*.me", "text/x-troff-me");
	this.add("*.sami", "application/x-sami");
	this.add("*.asx", "audio/x-ms-asx");
	this.add("*.mm", "text/x-troff-mm");
	this.add("*.mo", "application/x-gettext-translation");
	this.add("CMakeLists.txt", "text/x-cmake");
	this.add("*.ml", "text/x-ocaml");
	this.add("*.ms", "text/x-troff-ms");
	this.add("*.kfo", "application/x-kformula");
	this.add("*.rtf", "application/rtf");
	this.add("*.lhs", "text/x-literate-haskell");
	this.add("*.svg", "image/svg+xml");
	this.add("*.ppm", "image/x-portable-pixmap");
	this.add("*.nb", "application/mathematica");
	this.add("*.lhz", "application/x-lhz");
	this.add("*.pps", "application/vnd.ms-powerpoint");
	this.add("*.ppt", "application/vnd.ms-powerpoint");
	this.add("*.nc", "application/x-netcdf");
	this.add("*.icb", "image/x-tga");
	this.add("*.ica", "application/x-ica");
	this.add("*.mka", "audio/x-matroska");
	this.add("*.ppz", "application/vnd.ms-powerpoint");
	this.add("*.txt", "text/plain");
	this.add("*.rtx", "text/richtext");
	this.add("*.gedcom", "application/x-gedcom");
	this.add("*.cxx", "text/x-c++src");
	this.add("*.ico", "image/vnd.microsoft.icon");
	this.add("*.metalink", "application/metalink+xml");
	this.add("*.txz", "application/x-xz-compressed-tar");
	this.add("*.ics", "text/calendar");
	this.add("*.p10", "application/pkcs10");
	this.add("gnumakefile", "text/x-makefile");
	this.add("*.p12", "application/x-pkcs12");
	this.add("*.swf", "application/x-shockwave-flash");
	this.add("*.mkv", "video/x-matroska");
	this.add("*.idl", "text/x-idl");
	this.add("*.prc", "application/x-palm-database");
	this.add("*.mli", "text/x-ocaml");
	this.add("*.tar.lzo", "application/x-tzo");
	this.add("*.sxc", "application/vnd.sun.xml.calc");
	this.add("*.sxd", "application/vnd.sun.xml.draw");
	this.add("*.cert", "application/x-x509-ca-cert");
	this.add("*.avi", "video/x-msvideo");
	this.add("*.sxg", "application/vnd.sun.xml.writer.global");
	this.add("*.qtl", "application/x-quicktime-media-link");
	this.add("*.sxi", "application/vnd.sun.xml.impress");
	this.add("*.xac", "application/x-gnucash");
	this.add("*.djvu", "image/vnd.djvu");
	this.add("*.sxm", "application/vnd.sun.xml.math");
	this.add("winmail.dat", "application/vnd.ms-tnef");
	this.add("*.bz2", "application/x-bzip");
	this.add("*.ief", "image/ief");
	this.add("*.tzo", "application/x-tzo");
	this.add("*.pk", "application/x-tex-pk");
	this.add("*.pl", "application/x-perl");
	this.add("*.rvx", "video/vnd.rn-realvideo");
	this.add("*.sxw", "application/vnd.sun.xml.writer");
	this.add("*.php4", "application/x-php");
	this.add("*.mmf", "application/x-smaf");
	this.add("*.BLEND", "application/x-blender");
	this.add("*.kil", "application/x-killustrator");
	this.add("*.pm", "application/x-perl");
	this.add("*.ps", "application/postscript");
	this.add("*.awb", "audio/AMR-WB");
	this.add("*.psf", "application/x-font-linux-psf");
	this.add("*.psf", "audio/x-psf");
	this.add("*.pw", "application/x-pw");
	this.add("*.aifc", "audio/x-aiff");
	this.add("*.mml", "text/mathml");
	this.add("*.psd", "image/vnd.adobe.photoshop");
	this.add("*.mo3", "audio/x-mo3");
	this.add("*.aiff", "audio/x-aiff");
	this.add("*.gba", "application/x-gba-rom");
	this.add("*.awk", "application/x-awk");
	this.add("*.not", "text/x-mup");
	this.add("changelog", "text/x-changelog");
	this.add("*.sv4cpio", "application/x-sv4cpio");
	this.add("*%", "application/x-trash");
	this.add("*.po", "text/x-gettext-translation");
	this.add("*.hdf", "application/x-hdf");
	this.add("*.psw", "application/x-pocket-word");
	this.add("*.tar.bz", "application/x-bzip-compressed-tar");
	this.add("*.php3", "application/x-php");
	this.add("*.desktop", "application/x-desktop");
	this.add("*.fb2", "application/x-fictionbook+xml");
	this.add("*.wb1", "application/x-quattropro");
	this.add("*.wb2", "application/x-quattropro");
	this.add("*.ora", "image/openraster");
	this.add("*.wb3", "application/x-quattropro");
	this.add("*.iff", "image/x-iff");
	this.add("*.mp+", "audio/x-musepack");
	this.add("*.axa", "audio/annodex");
	this.add("*.orf", "image/x-olympus-orf");
	this.add("*.xbm", "image/x-xbitmap");
	this.add("copying", "text/x-copying");
	this.add("*.mp2", "audio/mp2");
	this.add("*.mp2", "video/mpeg");
	this.add("*.mp3", "audio/mpeg");
	this.add("*.mp4", "video/mp4");
	this.add("*.py", "text/x-python");
	this.add("*.kino", "application/smil");
	this.add("*.ra", "audio/vnd.rn-realaudio");
	this.add("*.rb", "application/x-ruby");
	this.add("*.icns", "image/x-icns");
	this.add("*.qt", "video/quicktime");
	this.add("*.xcf", "image/x-xcf");
	this.add("*.mng", "video/x-mng");
	this.add("*.xbl", "application/xml");
	this.add("*.axv", "video/annodex");
	this.add("*.cpio", "application/x-cpio");
	this.add("*.rm", "application/vnd.rn-realmedia");
	this.add("*.mod", "audio/x-mod");
	this.add("*.sv4crc", "application/x-sv4crc");
	this.add("*.rp", "image/vnd.rn-realpix");
	this.add("*.mof", "text/x-mof");
	this.add("*.wav", "audio/x-wav");
	this.add("*.rt", "text/vnd.rn-realtext");
	this.add("*.wax", "audio/x-ms-asx");
	this.add("*.rv", "video/vnd.rn-realvideo");
	this.add("*.moc", "text/x-moc");
	this.add("*.siag", "application/x-siag");
	this.add("*.pack", "application/x-java-pack200");
	this.add("*.gnumeric", "application/x-gnumeric");
	this.add("*.tnef", "application/vnd.ms-tnef");
	this.add("*.tpic", "image/x-tga");
	this.add("*.mov", "video/quicktime");
	this.add("*.smil", "application/smil");
	this.add("*.sh", "application/x-shellscript");
	this.add("*.divx", "video/x-msvideo");
	this.add("*.sk", "image/x-skencil");
	this.add("*.moov", "video/quicktime");
	this.add("*.mpc", "audio/x-musepack");
	this.add("*.so", "application/x-sharedlib");
	this.add("*.mpe", "video/mpeg");
	this.add("*.otc", "application/vnd.oasis.opendocument.chart-template");
	this.add("*.midi", "audio/midi");
	this.add("*.otf", "application/vnd.oasis.opendocument.formula-template");
	this.add("*.otf", "application/x-font-otf");
	this.add("*.otg", "application/vnd.oasis.opendocument.graphics-template");
	this.add("*.oth", "application/vnd.oasis.opendocument.text-web");
	this.add("*.mpg", "video/mpeg");
	this.add("*.mpp", "audio/x-musepack");
	this.add("*.otp", "application/vnd.oasis.opendocument.presentation-template");
	this.add("*~", "application/x-trash");
	this.add("*.ged", "application/x-gedcom");
	this.add("*.ots", "application/vnd.oasis.opendocument.spreadsheet-template");
	this.add("*.ott", "application/vnd.oasis.opendocument.text-template");
	this.add("*.tar.lzma", "application/x-lzma-compressed-tar");
	this.add("*.docm", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
	this.add("makefile", "text/x-makefile");
	this.add("*.wcm", "application/vnd.ms-works");
	this.add("*.tk", "text/x-tcl");
	this.add("*.gen", "application/x-genesis-rom");
	this.add("*.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
	this.add("*.log", "text/x-log");
	this.add("*.nsc", "application/x-netshow-channel");
	this.add("*.egon", "application/x-egon");
	this.add("*.tr", "text/troff");
	this.add("*.zip", "application/zip");
	this.add("*.kml", "application/vnd.google-earth.kml+xml");
	this.add("*.iptables", "text/x-iptables");
	this.add("*.m15", "audio/x-mod");
	this.add("*.wdb", "application/vnd.ms-works");
	this.add("*.kmz", "application/vnd.google-earth.kmz");
	this.add("*.shar", "application/x-shar");
	this.add("*.nsv", "video/x-nsv");
	this.add("*.texinfo", "text/x-texinfo");
	this.add("*.so.[0-9].*", "application/x-sharedlib");
	this.add("*.ui", "application/x-designer");
	this.add("*.ilbm", "image/x-ilbm");
	this.add("*.3ds", "image/x-3ds");
	this.add("*.vbs", "application/x-vbscript");
	this.add("*.mrl", "text/x-mrml");
	this.add("*.vcf", "text/directory");
	this.add("*.mrw", "image/x-minolta-mrw");
	this.add("*.jpeg", "image/jpeg");
	this.add("*.3g2", "video/3gpp");
	this.add("*.dar", "application/x-dar");
	this.add("*.tar.gz", "application/x-compressed-tar");
	this.add("*.p7b", "application/x-pkcs7-certificates");
	this.add("*.lzma", "application/x-lzma");
	this.add("*.vct", "text/directory");
	this.add("*.vcs", "text/calendar");
	this.add("*.msi", "application/x-msi");
	this.add("*.msi", "application/x-ms-win-installer");
	this.add("*.psid", "audio/prs.sid");
	this.add("*.kon", "application/x-kontour");
	this.add("*.blender", "application/x-blender");
	this.add("*.pyc", "application/x-python-bytecode");
	this.add("*.owl", "application/rdf+xml");
	this.add("*.vda", "image/x-tga");
	this.add("*.dbf", "application/x-dbf");
	this.add("*.p7s", "application/pkcs7-signature");
	this.add("*.pyo", "application/x-python-bytecode");
	this.add("*.msx", "application/x-msx-rom");
	this.add("*.epsf.bz2", "image/x-bzeps");
	this.add("*.cb7", "application/x-cb7");
	this.add("*.jng", "image/x-jng");
	this.add("*.texi", "text/x-texinfo");
	this.add("*.so.[0-9]", "application/x-sharedlib");
	this.add("*.wp", "application/vnd.wordperfect");
	this.add("*.kpm", "application/x-kpovmodeler");
	this.add("*.jp2", "image/jp2");
	this.add("*.wv", "audio/x-wavpack");
	this.add("*.cab", "application/vnd.ms-cab-compressed");
	this.add("*.kpr", "application/x-kpresenter");
	this.add("*.3ga", "video/3gpp");
	this.add("*.kpt", "application/x-kpresenter");
	this.add("*.n64", "application/x-n64-rom");
	this.add("*.mtm", "audio/x-mod");
	this.add("*.m2t", "video/mpeg");
	this.add("*.glade", "application/x-glade");
	this.add("*.oxt", "application/vnd.openofficeorg.extension");
	this.add("*.iso9660", "application/x-cd-image");
	this.add("*.gif", "image/gif");
	this.add("*.dcm", "application/dicom");
	this.add("*.ime", "text/x-iMelody");
	this.add("*.h++", "text/x-c++hdr");
	this.add("*.3gp", "video/3gpp");
	this.add("*.tar", "application/x-tar");
	this.add("*.dcr", "image/x-kodak-dcr");
	this.add("*.xi", "audio/x-xi");
	this.add("*.xm", "audio/x-xm");
	this.add("*.dcl", "text/x-dcl");
	this.add("*.3gpp", "video/3gpp");
	this.add("*.kdelnk", "application/x-desktop");
	this.add("*.vivo", "video/vivo");
	this.add("*.xz", "application/x-xz");
	this.add("*.imy", "text/x-iMelody");
	this.add("*.m3u", "audio/x-mpegurl");
	this.add("*.mup", "text/x-mup");
	this.add("*.kra", "application/x-krita");
	this.add("*.cbr", "application/x-cbr");
	this.add("*.m4b", "audio/x-m4b");
	this.add("*.cbt", "application/x-cbt");
	this.add("*.cpio.gz", "application/x-cpio-compressed");
	this.add("*.m4a", "audio/mp4");
	this.add("*.dds", "image/x-dds");
	this.add("*.jpe", "image/jpeg");
	this.add("*.jpg", "image/jpeg");
	this.add("*.cbz", "application/x-cbz");
	this.add("*.jpc", "image/jp2");
	this.add("*.tbz", "application/x-bzip-compressed-tar");
	this.add("*.eps.bz2", "image/x-bzeps");
	this.add("*.jpf", "image/jp2");
	this.add("*.k25", "image/x-kodak-k25");
	this.add("*.jpr", "application/x-jbuilder-project");
	this.add("*.7z", "application/x-7z-compressed");
	this.add("*.ins", "text/x-tex");
	this.add("*.deb", "application/x-deb");
	this.add("*.ini", "text/plain");
	this.add("*.psf.gz", "application/x-gz-font-linux-psf");
	this.add("*.jpx", "application/x-jbuilder-project");
	this.add("*.jpx", "image/jp2");
	this.add("*.m4v", "video/mp4");
	this.add("*.bak", "application/x-trash");
	this.add("*.rmvb", "application/vnd.rn-realmedia");
	this.add("gmon.out", "application/x-profile");
	this.add("*.perl", "application/x-perl");
	this.add("*.sam", "application/x-amipro");
	this.add("*.fig", "image/x-xfig");
	this.add("*.bcpio", "application/x-bcpio");
	this.add("*.gtar", "application/x-tar");
	this.add("*.ltx", "text/x-tex");
	this.add("*.lua", "text/x-lua");
	this.add("*.der", "application/x-x509-ca-cert");
	this.add("*.sav", "application/x-spss-sav");
	this.add("*.wk1", "application/vnd.lotus-1-2-3");
	this.add("*.tcl", "text/x-tcl");
	this.add("*.wk3", "application/vnd.lotus-1-2-3");
	this.add("*.wk4", "application/vnd.lotus-1-2-3");
	this.add("*.zoo", "application/x-zoo");
	this.add("*.xcf.gz", "image/x-compressed-xcf");
	this.add("*.qtif", "image/x-quicktime");
	this.add("*.oleo", "application/x-oleo");
	this.add("*.ksp", "application/x-kspread");
	this.add("*.ps.gz", "application/x-gzpostscript");
	this.add("*.opml", "text/x-opml+xml");
	this.add("*.cdf", "application/x-netcdf");
	this.add("*.vhd", "text/x-vhdl");
	this.add("*.xla", "application/vnd.ms-excel");
	this.add("*.inf", "text/plain");
	this.add("*.xlc", "application/vnd.ms-excel");
	this.add("*.xld", "application/vnd.ms-excel");
	this.add("*.xlf", "application/x-xliff");
	this.add("*.cdr", "application/vnd.corel-draw");
	this.add("*.xll", "application/vnd.ms-excel");
	this.add("*.xlm", "application/vnd.ms-excel");
	this.add("*.602", "application/x-t602");
	this.add("*.mxf", "application/mxf");
	this.add("*.xls", "application/vnd.ms-excel");
	this.add("*.xlt", "application/vnd.ms-excel");
	this.add("*.aac", "audio/mp4");
	this.add("*.xlsm", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
	this.add("*.xlw", "application/vnd.ms-excel");
	this.add("*.docbook", "application/docbook+xml");
	this.add("*.raf", "image/x-fuji-raf");
	this.add("*.fits", "image/fits");
	this.add("*.epsi.gz", "image/x-gzeps");
	this.add("*.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
	this.add("*.rdfs", "application/rdf+xml");
	this.add("*.ram", "application/ram");
	this.add("*.eif", "text/x-eiffel");
	this.add("*.scm", "text/x-scheme");
	this.add("*.ac3", "audio/ac3");
	this.add("*.rar", "application/x-rar");
	this.add("*.xmf", "audio/x-xmf");
	this.add("*.ras", "image/x-cmu-raster");
	this.add("*.cer", "application/x-x509-ca-cert");
	this.add("*.ldif", "text/x-ldif");
	this.add("*.kud", "application/x-kugar");
	this.add("*.rax", "audio/vnd.rn-realaudio");
	this.add("*.xml", "application/xml");
	this.add("*.gmo", "application/x-gettext-translation");
	this.add("*.xmi", "text/x-xmi");
	this.add("*.CSSL", "text/css");
	this.add("*.wks", "application/vnd.lotus-1-2-3");
	this.add("*.wks", "application/vnd.ms-works");
	this.add("*.tbz2", "application/x-bzip-compressed-tar");
	this.add("*.tex", "text/x-tex");
	this.add("*.raw", "image/x-panasonic-raw");
	this.add("*.sda", "application/vnd.stardivision.draw");
	this.add("*.sdc", "application/vnd.stardivision.calc");
	this.add("*.sdd", "application/vnd.stardivision.impress");
	this.add("*.bdf", "application/x-font-bdf");
	this.add("*.lwo", "image/x-lwo");
	this.add("*.lws", "image/x-lws");
	this.add("*.minipsf", "audio/x-minipsf");
	this.add("*.flc", "video/x-flic");
	this.add("*.gnc", "application/x-gnucash");
	this.add("*.gnd", "application/gnunet-directory");
	this.add("*.theme", "application/x-theme");
	this.add("*.sdp", "application/vnd.stardivision.impress");
	this.add("*.sdp", "application/sdp");
	this.add("*.fli", "video/x-flic");
	this.add("install", "text/x-install");
	this.add("*.sds", "application/vnd.stardivision.chart");
	this.add("*.abw", "application/x-abiword");
	this.add("*.j2k", "image/jp2");
	this.add("core", "application/x-core");
	this.add("*.sdw", "application/vnd.stardivision.writer");
	this.add("*.viv", "video/vivo");
	this.add("*.pdf.gz", "application/x-gzpdf");
	this.add("*.hpp", "text/x-c++hdr");
	this.add("*.flv", "video/x-flv");
	this.add("*.tiff", "image/tiff");
	this.add("*.flw", "application/x-kivio");
	this.add("*.ace", "application/x-ace");
	this.add("*.dvi.bz2", "application/x-bzdvi");
	this.add("*.dia", "application/x-dia-diagram");
	this.add("*.pcf.Z", "application/x-font-pcf");
	this.add("*.gnuplot", "application/x-gnuplot");
	this.add("*.wma", "audio/x-ms-wma");
	this.add("*.tga", "image/x-tga");
	this.add("*.cgm", "image/cgm");
	this.add("*.wmf", "image/x-wmf");
	this.add("*.torrent", "application/x-bittorrent");
	this.add("*.uil", "text/x-uil");
	this.add("*.vala", "text/x-vala");
	this.add("*.lwob", "image/x-lwo");
	this.add("*.kwd", "application/x-kword");
	this.add("*.wml", "text/vnd.wap.wml");
	this.add("*.iso", "application/x-cd-image");
	this.add("*.tgz", "application/x-compressed-tar");
	this.add("*.adb", "text/x-adasrc");
	this.add("*.wmv", "video/x-ms-wmv");
	this.add("*.wmx", "audio/x-ms-asx");
	this.add("*.rdf", "application/rdf+xml");
	this.add("*.kwt", "application/x-kword");
	this.add("*.vlc", "audio/x-mpegurl");
	this.add("*.lyx", "application/x-lyx");
	this.add("*.pdf.bz2", "application/x-bzpdf");
	this.add("*.chm", "application/x-chm");
	this.add("*.ufraw", "application/x-ufraw");
	this.add("*.gpg", "application/pgp-encrypted");
	this.add("*.ads", "text/x-adasrc");
	this.add("*.tar.Z", "application/x-tarz");
	this.add("*.xpm", "image/x-xpixmap");
	this.add("*.djv", "image/vnd.djvu");
	this.add("*.wp4", "application/vnd.wordperfect");
	this.add("*.wp5", "application/vnd.wordperfect");
	this.add("*.wp6", "application/vnd.wordperfect");
	this.add("*.xps", "application/vnd.ms-xpsdocument");
	this.add("*.lzh", "application/x-lha");
	this.add("*.lzo", "application/x-lzop");
	this.add("*.pak", "application/x-pak");
	this.add("*.sgf", "application/x-go-sgf");
	this.add("*.sylk", "text/spreadsheet");
	this.add("*.tif", "image/tiff");
	this.add("*.par2", "application/x-par2");
	this.add("*.sgi", "image/x-sgi");
	this.add("*.rej", "application/x-reject");
	this.add("*.sgl", "application/vnd.stardivision.writer");
	this.add("*.sgm", "text/sgml");
	this.add("*.xcf.bz2", "image/x-compressed-xcf");
	this.add("*.reg", "text/x-ms-regedit");
	this.add("*.pas", "text/x-pascal");
	this.add("*.emf", "image/x-emf");
	this.add("*.emp", "application/vnd.emusic-emusic_package");
	this.add("*.for", "text/x-fortran");
	this.add("*.pbm", "image/x-portable-bitmap");
	this.add("*.xbel", "application/x-xbel");
	this.add("*.gra", "application/x-graphite");
	this.add("*.afm", "application/x-font-afm");
	this.add("*.wpd", "application/vnd.wordperfect");
	this.add("*.shn", "application/x-shorten");
	this.add("*.wpg", "application/x-wpg");
	this.add("*.svgz", "image/svg+xml-compressed");
	this.add("*.cmake", "text/x-cmake");
	this.add("*.tar.bz2", "application/x-bzip-compressed-tar");
	this.add("*.wpl", "application/vnd.ms-wpl");
	this.add("*.dll", "application/x-sharedlib");
	this.add("*.ult", "audio/x-mod");
	this.add("*.wpp", "application/vnd.wordperfect");
	this.add("*.ent", "application/xml-external-parsed-entity");
	this.add("*.wps", "application/vnd.ms-works");
	this.add("*.669", "audio/x-mod");
	this.add("*.jnlp", "application/x-java-jnlp-file");
	this.add("*.pcf", "application/x-font-pcf");
	this.add("*.pcf", "application/x-cisco-vpn-settings");
	this.add("*.pcd", "image/x-photo-cd");
	this.add("*.bib", "text/x-bibtex");
	this.add("*.rgb", "image/x-rgb");
	this.add("*.sid", "audio/prs.sid");
	this.add("*.pcl", "application/vnd.hp-pcl");
	this.add("*.c++", "text/x-c++src");
	this.add("*.htm", "text/html");
	this.add("*.voc", "audio/x-voc");
	this.add("*.sik", "application/x-trash");
	this.add("*.vapi", "text/x-vala");
	this.add("*.bin", "application/octet-stream");
	this.add("*.vob", "video/mpeg");
	this.add("*.gsf", "application/x-font-type1");
	this.add("*.sk1", "image/x-skencil");
	this.add("*.ag", "image/x-applix-graphics");
	this.add("*.ai", "application/illustrator");
	this.add("*.sis", "application/vnd.symbian.install");
	this.add("*.sit", "application/x-stuffit");
	this.add("*.al", "application/x-perl");
	this.add("*.gsm", "audio/x-gsm");
	this.add("*.siv", "application/sieve");
	this.add("*.vor", "application/vnd.stardivision.writer");
	this.add("*.xsl", "application/xml");
	this.add("*.diff", "text/x-patch");
	this.add("*.pdb", "application/x-aportisdoc");
	this.add("*.pdb", "application/x-palm-database");
	this.add("*.pdc", "application/x-aportisdoc");
	this.add("*.as", "application/x-applix-spreadsheet");
	this.add("*.au", "audio/basic");
	this.add("*.pdf", "application/pdf");
	this.add("*.aw", "application/x-applix-word");
	this.add("*.obj", "application/x-tgif");
	this.add("*.sgml", "text/sgml");
	this.add("*.pcx", "image/x-pcx");
	this.add("*.dng", "image/x-adobe-dng");
	this.add("*.uni", "audio/x-mod");
	this.add("*.wbmp", "image/vnd.wap.wbmp");
	this.add("*.wri", "application/x-mswrite");
	this.add("*.java", "text/x-java");
	this.add("*.wrl", "model/vrml");
	this.add("*.flac", "audio/x-flac");
	this.add("*.cls", "text/x-tex");
	this.add("*.eps", "image/x-eps");
	this.add("*.kexi", "application/x-kexiproject-sqlite2");
	this.add("*.kexi", "application/x-kexiproject-sqlite3");
	this.add("*.tlz", "application/x-lzma-compressed-tar");
	this.add("*.pef", "image/x-pentax-pef");
	this.add("*.aif", "audio/x-aiff");
	this.add("*.ocl", "text/x-ocl");
	this.add("*.class", "application/x-java");
	this.add("*.doc", "application/msword");
	this.add("*.pem", "application/x-x509-ca-cert");
	this.add("*.bz", "application/x-bzip");
	this.add("makefile", "text/x-makefile");
	this.add("*.x3f", "image/x-sigma-x3f");
	this.add("*.cc", "text/x-c++src");
	this.add("*.skr", "application/pgp-keys");
	this.add("*.xul", "application/vnd.mozilla.xul+xml");
	this.add("*.xul", "application/vnd.mozilla.xul+xml");
	this.add("*.dot", "application/msword-template");
	this.add("*.dot", "text/vnd.graphviz");
	this.add("*.oda", "application/oda");
	this.add("*.odb", "application/vnd.oasis.opendocument.database");
	this.add("*.odc", "application/vnd.oasis.opendocument.chart");
	this.add("*.pict", "image/x-pict");
	this.add("*.pfb", "application/x-font-type1");
	this.add("*.odf", "application/vnd.oasis.opendocument.formula");
	this.add("*.odg", "application/vnd.oasis.opendocument.graphics");
	this.add("*.karbon", "application/x-karbon");
	this.add("*.odi", "application/vnd.oasis.opendocument.image");
	this.add("*.hwp", "application/x-hwp");
	this.add("*.xhtml", "application/xhtml+xml");
	this.add("*.odm", "application/vnd.oasis.opendocument.text-master");
	this.add("*.hwt", "application/x-hwt");
	this.add("credits", "text/x-credits");
	this.add("*.odp", "application/vnd.oasis.opendocument.presentation");
	this.add("*.tnf", "application/vnd.ms-tnef");
	this.add("*.pfa", "application/x-font-type1");
	this.add("*.ods", "application/vnd.oasis.opendocument.spreadsheet");
	this.add("*.odt", "application/vnd.oasis.opendocument.text");
	this.add("*.dc", "application/x-dc-rom");
	this.add("*.slk", "text/spreadsheet");
	this.add("*.erl", "text/x-erlang");
	this.add("*.pfx", "application/x-pkcs12");
	this.add("*.mab", "application/x-markaby");
	this.add("*.sisx", "x-epoc/x-sisx-app");
	this.add("*.ustar", "application/x-ustar");
	this.add("*.gvp", "text/x-google-video-pointer");
	this.add("*.dv", "video/dv");
	this.add("*.man", "application/x-troff-man");
	this.add("*.qif", "application/x-qw");
	this.add("*.qif", "image/x-quicktime");
	this.add("*.smd", "application/vnd.stardivision.mail");
	this.add("*.toc", "application/x-cdrdao-toc");
	this.add("*.smf", "application/vnd.stardivision.math");
	this.add("*.pgm", "image/x-portable-graymap");
	this.add("*.pgn", "application/x-chess-pgn");
	this.add("*.smi", "application/smil");
	this.add("*.smi", "application/x-sami");
	this.add("*.pgp", "application/pgp-encrypted");
	this.add("*.cs", "text/x-csharp");
	this.add("*.cs", "text/x-csharp");
	this.add("*.sml", "application/smil");
	this.add("*.smc", "application/x-snes-rom");
	this.add("*.xwd", "image/x-xwindowdump");
	this.add("*.bmp", "image/bmp");
	this.add("*.blend", "application/x-blender");
	this.add("*.com", "application/x-ms-dos-executable");
	this.add("*.atom", "application/atom+xml");
	this.add("*.sms", "application/x-sms-rom");
	this.add("*.el", "text/x-emacs-lisp");
	this.add("*.hxx", "text/x-c++hdr");
	this.add("*.g3", "image/fax-g3");
	this.add("*.vst", "image/x-tga");
	this.add("*.es", "application/ecmascript");
	this.add("*.PAR2", "application/x-par2");
	this.add("*.eps.gz", "image/x-gzeps");
	this.add("*.rle", "image/rle");
	this.add("*.snd", "audio/basic");
	this.add("*.ez", "application/andrew-inset");
	this.add("*.psflib", "audio/x-psflib");
	this.add("*.nds", "application/x-nintendo-ds-rom");
	this.add("*.php", "application/x-php");
	this.add("*.wvc", "audio/x-wavpack-correction");
	this.add("*.123", "application/vnd.lotus-1-2-3");
	this.add("*.uri", "text/x-uri");
	this.add("*.url", "text/x-uri");
	this.add("*.abw.CRASHED", "application/x-abiword");
	this.add("*.cr2", "image/x-canon-cr2");
	this.add("*.tar.xz", "application/x-xz-compressed-tar");
	this.add("*.roff", "text/troff");
	this.add("*.fl", "application/x-fluid");
	this.add("*.alz", "application/x-alz");
	this.add("*.oga", "audio/ogg");
	this.add("*.wvp", "audio/x-wavpack");
	this.add("*.nef", "image/x-nikon-nef");
	this.add("*,v", "text/plain");
	this.add("*.C", "text/x-c++src");
	this.add("*.themepack", "application/x-windows-themepack");
	this.add("*.ogg", "audio/ogg");
	this.add("*.ogg", "audio/x-vorbis+ogg");
	this.add("*.ogg", "audio/x-flac+ogg");
	this.add("*.ogg", "audio/x-speex+ogg");
	this.add("*.ogg", "video/x-theora+ogg");
	this.add("*.wvx", "audio/x-ms-asx");
	this.add("*.fo", "text/x-xslfo");
	this.add("*.etx", "text/x-setext");
	this.add("*.pptm", "application/vnd.openxmlformats-officedocument.presentationml.presentation");
	this.add("readme", "text/x-readme");
	this.add("todo", "text/x-todo");
	this.add("license", "text/x-license");
	this.add("*.version", "text/x-version");
	this.add("Makefile.*", "text/x-makefile");
	this.add("*.dmg", "application/x-apple-diskimage");
	this.add("*.swp", "application/x-igelle-software-package");
	this.add("*.squashfs", "application/x-igelle-diskimage-squashfs");
	this.add("*.img", "application/x-igelle-diskimage");
	this.add("*.eq", "text/x-eqela-src");
	this.add("*.equity", "text/x-eqela-equity-src");
	this.add("*.eqic", "text/x-eqela-eqic-config");
	this.add("*.config", "text/x-config");
	this.add("*.eqlib", "application/x-eqela-library");
	this.add("*.eqlibx", "application/x-eqela-library-encrypted");
	this.add("*.apk", "application/vnd.android.package-archive");
	this.add("*.eo", "application/x-eqela-object");
	this.add("*.eo1", "application/x-eqela-object-level-1");
	this.add("*.eo2", "application/x-eqela-object-level-2");
	this.add("*.eo3", "application/x-eqela-object-level-3");
	this.add("*.eo4", "application/x-eqela-object-level-4");
	this.add("*.eo5", "application/x-eqela-object-level-5");
	this.add("*.iga", "application/x-igelle-archive");
	this.add("*.ipa", "application/octet-stream");
	this.add("*.xap", "application/x-silverlight-app");
	this.add("*.webapp", "application/x-web-app-manifest+json");
	this.add("*.json", "application/json");
	this.add("*.properties", "application/properties");
	this.add(".classpath", "application/xml");
	this.add(".project", "application/xml");
	this.add("*.bat", "application/x-msdos-program");
	this.add("*.yml", "text/yaml");
	this.add("*.yaml", "text/yaml");
	this.add("*.scss", "text/x-scss");
	this.add("*.gradle", "application/x-gradle");
	this.add("manifest.mf", "application/x-manifest");
	this.add("*.vm", "application/x-velocity");
	this.add("*.jade", "application/x-jade");
	this.add("*.xsd", "application/xml");
	this.add("*.eot", "application/vnd.ms-fontobject");
	this.add("*.woff", "application/x-font-woff");
	this.add("*.woff2", "application/x-font-woff");
	this.add("*.svf", "application/x-font-svf");
	this.add("*.fnt", "application/x-font-fnt");
	this.add("*.wsdl", "application/wsdl+xml");
	this.add("*.jsx", "application/javascript");
	this.add("*.ts", "application/x-typescript");
	this.add("*.tsx", "application/x-typescript");
	this.add("*.jks", "application/x-jks");
	this.add("*.jsp", "application/x-jsp");
	this.add("*.pom", "application/x-maven-pom");
	this.add(".gitignore", "application/x-gitignore");
	this.add("org.eclipse.jdt.core.prefs", "application/x-eclipse-prefs");
	this.add("org.eclipse.buildship.core.prefs", "application/x-eclipse-prefs");
	this.add("*.vsd", "application/vnd.visio");
	this.add(".editorconfig", "application/x-editorconfig");
	this.add(".htaccess", "application/x-htaccess");
	this.add("*.mxml", "application/xml");
	this.add("*.tld", "application/xml");
	this.add("*.csproj", "application/csproj+xml");
	this.add("*.sln", "application/x-sln");
	this.add("*.elm", "application/x-elm");
	this.add("*.scala", "application/x-scala");
	this.add("dockerfile", "application/x-docker-dockerfile");
	this.add("gemfile", "application/x-gem-gemfile");
	this.add("*.sbt", "application/x-scala-sbt");
};

JkMimeMimeTypeRegistry.prototype.getTypeForExtension = function(ext) {
	if(!(ext != null)) {
		return null;
	}
	return JkLangMap.get(this.htMime, (JkLangString.toLowerCase(ext)));
};

JkMimeMimeTypeRegistry.prototype.getTypeForFile = function(f) {
	if(!(f != null)) {
		return "application/unknown";
	}
	return this.getMimeType((f.getBasename()));
};

JkMimeMimeTypeRegistry.prototype.getMimeType = function(str) {
	var v = null;
	if(str != null) {
		var mime = null;
		var ld = JkLangString.getLastIndexOfCharacter(str, '.'.charCodeAt(), (-1));
		if(ld >= 0) {
			mime = JkLangString.getEndOfString(str, (ld + 1));
		}
		v = JkLangMap.get(this.htMime, (JkLangString.toLowerCase(mime)));
		if(JkLangString.isEmpty(v)) {
			v = JkLangMap.get(this.htMime, (JkLangString.toLowerCase(str)));
		}
	}
	if(JkLangString.isEmpty(v)) {
		v = "application/unknown";
	}
	return v;
};

JkMimeMimeTypeRegistry.prototype.getExtension = function(mimeType) {
	return JkLangMap.get(this.htExt, mimeType);
};

JkMimeMimeTypeRegistry.prototype.add = function(pattern, mimeType) {
	var v = false;
	if(pattern == null || mimeType == null) {
		;
	}
	else if(JkLangString.startsWith(pattern, ".", 0) == true) {
		var key = JkLangString.getSubString(pattern, 1, (JkLangString.getLength(pattern) - 1));
		JkLangMap.set(this.htMime, key, mimeType);
		JkLangMap.set(this.htExt, mimeType, key);
		v = true;
	}
	else if(JkLangString.startsWith(pattern, "*.", 0) == true) {
		var key1 = JkLangString.getSubString(pattern, 2, (JkLangString.getLength(pattern) - 2));
		JkLangMap.set(this.htMime, key1, mimeType);
		JkLangMap.set(this.htExt, mimeType, key1);
		v = true;
	}
	else if(JkLangString.startsWith(pattern, "#", 0) == true) {
		;
	}
	else {
		JkLangMap.set(this.htMime, pattern, mimeType);
		JkLangMap.set(this.htExt, mimeType, pattern);
		v = true;
	}
	return v;
};

JkMimeMimeTypeRegistry.prototype.read = function(file) {
	if(!(file != null)) {
		return false;
	}
	var buf = JkIoPrintReader.forReader((file.read()));
	if(!(buf != null)) {
		return false;
	}
	var n = 0;
	while(true){
		var line = buf.readLine();
		if(!(line != null)) {
			break;
		}
		var va = JkLangString.split(line, ':'.charCodeAt(), 0);
		var val = JkLangVector.iterate(va);
		if(val != null) {
			var front = val.next();
			var back = val.next();
			if(front != null) {
				front = JkLangString.strip(front);
			}
			if(back != null) {
				back = JkLangString.strip(back);
			}
			if(this.add(front, back)) {
				n++;
			}
		}
	}
	return true;
};

JkMimeMimeTypeRegistry.IS_INSTANCE = function(o) {
	return o != null && o._t != null && o._t["JkMimeMimeTypeRegistry"] === true;
};

JkMimeMimeTypeRegistry.sharedInstance = null;
